### ISSUE TITLE
Plug-in IoT device to Test-Station for testing

### ISSUE THREAD

**Issue by xBlade58** [xBlade58/smart-meter-platform-page#10]
As we already were provided an IoT device by our lecturer, we should test it by plugging it in to the Test-Station.

- check if data can be read
- to verify this, the "Basic IoT Edge" should show the received images

**Comment by bellerstefan** [comment]
![Image](https://github.com/xBlade58/smart-meter-platform-page/assets/16673073/0ba19976-35b0-451c-8c6a-9b17975b9b5e)

🥳

**Comment by bellerstefan** [comment]
![Image](https://github.com/xBlade58/smart-meter-platform-page/assets/16673073/2f78ad82-ad3d-422b-9440-1090932ec5f2)

**Comment by xBlade58** [comment]
Python mqtt client successfully receives messages from iot device via emqx broker

![mqtt_pyhton_client_receives_messages_iot](https://github.com/xBlade58/smart-meter-platform-page/assets/79519335/b99b7161-3c32-4828-80b7-279cd846a682)
