### ISSUE TITLE
Create first draft of specification for "IoT Edge" component

### ISSUE THREAD

**Issue by xBlade58** [xBlade58/smart-meter-platform-page#7]

**Comment by justinstroehleFH** [comment]
Kp wie i dean Pull request dazu linken kann

**Comment by xBlade58** [comment]
> Kp wie i dean Pull request dazu linken kann

Mit #13 ;).

**Comment by xBlade58** [comment]
oder wenn im PR bisch einfach "#ISSUE_NUMMER" igia
