### ISSUE TITLE
Implement Data Simulator

### ISSUE THREAD

**Issue by xBlade58** [xBlade58/smart-meter-platform-page#9]
Needed for simulation of IoT device.

- read from sample data set and publish message to a topic in a certain interval.
- run as docker container

**Comment by bellerstefan** [comment]
Maybe create a Docker file to start the application and use e.g. https://hub.docker.com/_/eclipse-mosquitto as a broker

**Comment by xBlade58** [comment]
See https://github.com/xBlade58/smart-meter-platform-data-simulator

**Comment by bellerstefan** [comment]
Issue is merged to main on specified repository. 

It can be started using Docker Compose.

Producer Prodcues Messages

Consumer Consumes them

Docker logs has probably an optimization going on to not continuously display the logs - in a other subscriber it could be verified that the messages are arriving in the specified amount of time!

Test Result
OK
